version: '3'

services:
  postgres:
    image: "postgres:14-alpine"
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cataloguser
      POSTGRES_PASSWORD: cataloguser

    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./db-data/:/db-data/"

volumes:
  pgdata:
